coverage:
  range: "70...100"
  round: down
  precision: 2
  
  status:
    project:
      default:
        enabled: yes
        target: 94%
        threshold: 5%
        
    patch:
      default:
        enabled: yes
        target: 85%
        threshold: 5%
        
    changes: no
    
